### ISSUE TITLE
onSave方法触发后，怎么取值？

### ISSUE THREAD

**Issue by kurisLei** [kkfor/for-editor#20]
如题，该方法返回的是undefined，希望作者可以再完善一下文档，支持了，谢谢！

**Comment by kkfor** [comment]
@kurisLei 感谢反馈，目前状态都是存在与父组件，不存在于for-editor组件中，正在考虑近期重构并扩展功能

**Comment by kkfor** [comment]
已修改:onSave回调中返回文章内容
