### ISSUE TITLE
换行无效问题

### ISSUE THREAD

**Issue by WandW** [kkfor/for-editor#29]
![image](https://user-images.githubusercontent.com/17613612/61691054-4bfdd180-ad5d-11e9-8eca-3f1af8c2f07e.png)
如图输入回车无法正常换行
游览器采用  谷歌游览器 73.0.3683.75

**Comment by WandW** [comment]
并且右侧预览无法显示

**Comment by kkfor** [comment]
@WandW 此编辑器为md编辑器，建议看一看markdown语法

**Comment by WandW** [comment]
是编辑器部分无法进行换行，预览也无法显示。
demo 并没有出现这种情况

**Comment by kkfor** [comment]
@WandW 此组件为受控组件，用法请仔细查看文档，类input用法

**Comment by WandW** [comment]
感谢解答问题
