### ISSUE TITLE
单双栏按钮和预览按钮状态问题

### ISSUE THREAD

**Issue by pipipi-pikachu** [kkfor/for-editor#34]
打开双栏后，toolbar上同时显示预览按钮处于激活状态，此时再点击预览按钮，编辑区域恢复到了单栏的状态，但是双栏按钮依然处于激活状态。

认为预览按钮和双栏按钮只能同一时间激活一个即可

**Comment by kkfor** [comment]
@pipipi-pikachu 双栏可单独激活但无效果(目前认为没有必要编辑与编辑双栏模式)，双栏激活模式下点击预览为编辑与预览双栏模式。双栏模式不激活情况下点击预览为单栏预览模式
