### ISSUE TITLE
TypeScript 定义有问题

### ISSUE THREAD

**Issue by jas0ncn** [kkfor/for-editor#35]
你这个库不是使用 ts 写的吗？可以再 `tsconfig.json` 的 `compiler options` 里加一个 `declaration`，自动生成类型定义，而不是你这样定义啊。。。所有的 props 都是必选的吗？整个项目都挂了....

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by kkfor** [comment]
@jas0ncn 感谢指点
