### ISSUE TITLE
使用TS，onChange的事件传入类型报错！

### ISSUE THREAD

**Issue by Feafortecsy** [kkfor/for-editor#36]
1. React Hook + TS。onChange事件无法传入，会有类型报错，我的解决方法在下图。不知您这边是怎么处理的。
![img1](https://user-images.githubusercontent.com/31724313/64074771-468f9180-cce2-11e9-941a-a1d68a8fa04c.png)
2. 看了下源码，onChange事件是可选，所以会出现这个问题是不是因为打包的时候出了什么意外状况？
![img2](https://user-images.githubusercontent.com/31724313/64074905-fc0f1480-cce3-11e9-84b9-14246288b0ff.png)

**Comment by kkfor** [comment]
@Feafortecsy 感谢反馈，已修复ts下类型问题。
