### ISSUE TITLE
如何获取右侧的html的数据呢？

### ISSUE THREAD

**Issue by 2fps** [kkfor/for-editor#6]
是否可以考虑在onSave时，用参数传出右侧的html数据呢？

**Comment by kkfor** [comment]
谢谢建议，后续版本考虑传出html结构数据

**Comment by zhang-jiashun** [comment]
作者用的是 [marked](https://github.com/markedjs/marked), 可以自己引入 marked，在onSave时调用 marked(value)， 返回的值就是 html

**Comment by 2fps** [comment]
可以的，感谢建议
