### ISSUE TITLE
可不可设置一个flag，让用户直接调用【显示】的功能，而不需要【编辑】的功能？

### ISSUE THREAD

**Issue by linzelong95** [kkfor/for-editor#9]
如题。觉得该编辑器的显示功能不错，有时候只需要显示，而不需要编辑。谢谢。

**Comment by KTDefTnT** [comment]
深表赞同 我也碰到了这个问题，再用reactMarkdown显示不一致了

**Comment by 2fps** [comment]
样式都在index.scss中，外层套个class是for-markdown-preview的就行了啊，内层存放已经转成标签的内容

**Comment by kkfor** [comment]
感谢建议，目前已支持仅预览模式
